[package]
name = "aoc2023"
version = "0.1.0"
authors = ["Victor Kropp <victor@kropp.name>"]

[[bin]]
name = "day01"
path = "day01.rs"

[[bin]]
name = "day02"
path = "day02.rs"

[[bin]]
name = "day03"
path = "day03.rs"
